### ISSUE TITLE
Switching video source?

### ISSUE THREAD

**Issue by kajala** [infobip/infobip-rtc-js-1.x-deprecated#1]
Hi, how can I switch the camera using the SDK? For example if I have built-in webcam and external webcam connected to a laptop. Thanks

**Comment by mmujic** [comment]
Hi,
you can use https://github.com/infobip/infobip-rtc-js/wiki/InfobipRTC#getVideoInputDevices to get all available video devices and then call https://github.com/infobip/infobip-rtc-js/wiki/Call#setVideoInputDevice method with deviceId you want to use.
